menu:
    Index: /
    Archive: /archives/
#    Weibo: 
    GitHub: https://github.com/upeoe
    Rss: /atom.xml

favicon: /favicon.jpg
logo: /favicon.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo: 

# Analytics
# google-analytics:
# ga: 

# Copyright Infomation
startyear: 2015
